parameters:

services:
    Overblog\GraphQLConfigurationSdlBundle\ConfigurationSdlParser:
        arguments:
            - "%graphql.configuration.directories.sdl%"
        tags:
            - { name: "overblog_graphql.configuration.provider" }
