parameters:

services:
    Overblog\GraphQLConfigurationYamlBundle\ConfigurationYamlParser:
        arguments:
            - "%graphql.configuration.directories.yaml%"
        tags:
            - { name: "overblog_graphql.configuration.provider" }
