parameters: ~

services:
    Overblog\GraphQLConfigurationMetadataBundle\Reader\AnnotationReader:
        public: true

    Overblog\GraphQLConfigurationMetadataBundle\Reader\AttributeReader:
        public: true

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler:
        abstract: true
        arguments:
            - '@Overblog\GraphQLConfigurationMetadataBundle\ClassesTypesMap'
            - '@overblog_graphql.metadata.reader'
            - '@Overblog\GraphQLConfigurationMetadataBundle\TypeGuesser\TypeGuesser'
            - '%overblog_graphql.schemas%'

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\EnumHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Enum',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\InputHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Input',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\InterfaceHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\TypeInterface',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\ScalarHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Scalar',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\ObjectHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Type',
              }
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Provider',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\UnionHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Union',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\RelayEdgeHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Relay\Edge',
              }

    Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\RelayConnectionHandler:
        parent: Overblog\GraphQLConfigurationMetadataBundle\MetadataHandler\MetadataHandler
        tags:
            - {
                  name: 'overblog_graphql.metadata.handler',
                  annotationClass: 'Overblog\GraphQLConfigurationMetadataBundle\Metadata\Relay\Connection',
              }
