parameters: ~

services:
    overblog_graphql.arguments_transformer: '@Overblog\GraphQLConfigurationMetadataBundle\Transformer\ArgumentsTransformer'

    Overblog\GraphQLConfigurationMetadataBundle\ConfigurationMetadataParser:
        arguments:
            - "@overblog_graphql.metadata.reader"
            - '@Overblog\GraphQLConfigurationMetadataBundle\ClassesTypesMap'
            - !tagged_iterator { tag: "overblog_graphql.metadata.handler", index_by: "annotationClass" }
            - "%graphql.configuration.directories.metadata%"
        tags:
            - { name: "overblog_graphql.configuration.provider" }

    Overblog\GraphQLConfigurationMetadataBundle\ClassesTypesMap:
        public: true
        arguments:
            - '@Symfony\Contracts\Cache\CacheInterface'

    Overblog\GraphQLConfigurationMetadataBundle\Transformer\ArgumentsTransformer:
        arguments:
            - "@?validator"
            - '@Overblog\GraphQLConfigurationMetadataBundle\ClassesTypesMap'

    Overblog\GraphQLConfigurationMetadataBundle\ExpressionFunction\Arguments:
        tags: ["overblog_graphql.expression_function"]
