services:
    _defaults:
        autowire: true

    Overblog\GraphQLConfigurationMetadataBundle\TypeGuesser\TypeGuesser:
        arguments:
            - !tagged_iterator 'overblog_graphql.metadata.type_guesser_extension'

    Overblog\GraphQLConfigurationMetadataBundle\TypeGuesser\Extension\DocBlockTypeGuesserExtension:
        tags:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 100 }

    Overblog\GraphQLConfigurationMetadataBundle\TypeGuesser\Extension\TypeHintTypeGuesserExtension:
        tags:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 50 }

    Overblog\GraphQLConfigurationMetadataBundle\TypeGuesser\Extension\DoctrineTypeGuesserExtension:
        tags:
            - { name: 'overblog_graphql.metadata.type_guesser_extension', priority: 0 }
        arguments:
            $doctrineMapping: '%graphql.configuration.metadata.type_guesser.doctrine_mapping%'
